spring:
  application:
    name: spring-cloud-dubbo-provider
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 25000
server:
  port: 0