spring:
  application:
    name: spring-cloud-dubbo-provider
dubbo:
  application:
    name: dubbo-provider
  config-center:
    timeout: 10000
  protocol:
    name: dubbo
    port: 20880

  registry:
    address: zookeeper://192.168.56.102:2181
    timeout: 25000
  #是否导出服务
  provider:
    export: true
server:
  port: 0