spring:
  application:
    name: spring-cloud-dubbo-provider
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 25000
  config-center:
    timeout: 10000
server:
  port: 0