spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
        username: nacos
        password: nacos
    gateway: #gateway通过nacos实现自动转发
      discovery:
        locator:
          enabled: true #locator.enabled是自动根据URL规则实现路由转发

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'