spring:
  application:
    name: spring-cloud-dubbo-consumer
dubbo:
  application:
    name: dubbo-consumer
  config-center:
    timeout: 10000
  registry:
    address: zookeeper://192.168.56.102:2181
    timeout: 10000