server:
  port: 8080
#注意在连接redis时要注释掉bind 127.0.0.1
#redis设置密码requirepass 123456 再次进入客户端操作需要auth 123456
spring:
  redis:
    host: 192.168.56.100
    port: 6379
    timeout: 10000
    password:
    lettuce:
      pool:
        max-wait: 16
        max-active: 16
        max-idle: 16
        min-idle: 1
    database: 0