spring:
  redis:
    host: 192.168.56.100
    port: 6379
    timeout: 3000
    password:
    lettuce:
      pool:
        max-wait: 16
        max-active: 16
        max-idle: 16
        min-idle: 1
      shutdown-timeout: 10000ms  # 关闭超时时间
    database: 0
